colors:
    statusbar:
        caret:
            bg: "#6c71c4"
            fg: "#93a1a1"
        command:
            bg: "#859900"
            fg: "#00161C"
            private:
                bg: "black"
        insert:
            bg: "#859900"
            fg: "#00161C"
        normal:
            bg: "#00161C"
            fg: "#93a1a1"
        private:
            bg: "#00161C"
            fg: "#93a1a1"
        progress:
            bg: "#93a1a1"
        url:
            fg: "#93a1a1"
            error:
                fg: "#dc322f"
            hover:
                fg: "#859900"
            success:
                http:
                    fg: "#93a1a1"
                https:
                    fg: "#859900"
            warn:
                fg: "#b58900"
    tabs:
        bar:
            bg: "#00161C"
        even:
            fg: "#93a1a1"
            bg: "#00161C"
        odd:
            fg: "#93a1a1"
            bg: "#003745"
        selected:
            even:
                fg: "#00161C"
                bg: "#859900"
            odd:
                fg: "#003745"
                bg: "#859900"
    completion:
        category:
            bg: "#859900"
            fg: "#00161C"
            border:
                bottom: "#00161C"
                top: "#859900"
        even:
            bg: "#00161C"
        odd:
            bg: "#003745"
        item:
            selected:
                bg: "#859900"
                fg: "#00161C"
                border:
                    bottom: "#859900"
                    top: "#859900"
        match:
            fg: "#dc322f"
        scrollbar:
            bg: "#93a1a1"
            fg: "#00161C"
    downloads:
        bar:
            bg: "#00161C"
        error:
            fg: "#93a1a1"
            bg: "#dc322f"
        start:
            fg: "#93a1a1"
            bg: "#6c71c4"
        stop:
            fg: "#00161C"
            bg: "#859900"
    hints:
        fg: "#00161C"
        bg: "#859900"
        match:
            fg: "#b58900"
    keyhint:
        fg: "#00161C"
        bg: "#859900"
        suffix:
            fg: "#b58900"
    messages:
        error:
            fg: "#93a1a1"
            bg: "#dc322f"
            border: "#dc322f"
        info:
            fg: "#00161C"
            bg: "#859900"
            border: "#859900"
        warning:
            fg: "#93a1a1"
            bg: "#b58900"
            border: "#b58900"
    prompts:
        fg: "#93a1a1"
        bg: "#00161C"
        border: "#00161C"
        selected:
            bg: "#b58900"
    webpage:
        bg: "#93a1a1"
hints:
    border: "1px solid #93a1a1"
